name: NLP Contract Analysis CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download spaCy model
        run: python -m spacy download en_core_web_sm

      - name: Run NLP contract analysis script
        run: python contract_analysis.py

      - name: Run unit tests
        run: PYTHONPATH=$PWD pytest tests/

      - name: Run NLP model & log performance
        run: |
          python contract_analysis.py
          cat log_performance.txt

      - name: Generate performance chart
        run: python contract_analysis.py

      - name: Upload performance chart
        uses: actions/upload-artifact@v4  
        with:
          name: Performance Chart
          path: performance_chart.png
         
      - name: Install Streamlit
        run: pip install streamlit
      
      - name: Run Streamlit App (Test Mode)
        run: streamlit run app.py --server.headless true &
      
      - name: Download spaCy model
        run: python -m spacy download en_core_web_sm
